title: "Xavier Shay's Blog"
url:   http://rhnh.net
feed:  http://feeds.feedburner.com/rhnh
author: 
  name:  Xavier Shay
  email: notreal@rhnh.net
  open_id:
    - http://rhnh.net/
    - https://xaviershay.myid.net/

# Delete the following section if your site will not be acting as an OpenID delegate
open_id_delegation:
  server:   http://server.myid.net/server
  delegate: http://xaviershay.myid.net/
