title: Robot Has No Heart
url:   http://rhnh.net
author: 
  name:    Xavier Shay
  open_id: http://rhnh.net

open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://rhnh.net
