title: "Xavier Shay's Blog"
url:   http://rhnh.net
feed:  http://feeds.feedburner.com/rhnh
author: 
  name:    Xavier Shay
  open_id: http://rhnh.net
  email:   notreal@rhnh.net

# Delete the following section if your site will not be acting as an OpenID delegate
open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://rhnh.net
