title: Robot Has No Heart
url:   http://rhnh.net
author: 
  name:    Xavier Shay
  open_id: http://rhnh.net

# Delete the following section if your site will not be acting as an OpenID delegate
open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://rhnh.net
